update providers
set
  latitude = case
    when lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%westlands%' then '-1.2675000'
    when lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%kilimani%' then '-1.2925000'
    when lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%lavington%' then '-1.2833000'
    when lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%kileleshwa%' then '-1.2802000'
    when lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%parklands%' then '-1.2615000'
    when lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%upper hill%' then '-1.3003000'
    when lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%ngong road%' then '-1.3009000'
    when lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%langata%' then '-1.3499000'
    when lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%karen%' then '-1.3194000'
    when lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%ruaka%' then '-1.2102000'
    when lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%runda%' then '-1.2241000'
    when lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%kasarani%' then '-1.2234000'
    when lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%embakasi%' then '-1.3156000'
    when lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%donholm%' then '-1.2998000'
    when lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%south b%' then '-1.3085000'
    when lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%southb%' then '-1.3085000'
    when lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%south c%' then '-1.3203000'
    when lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%southc%' then '-1.3203000'
    when lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%thika road%' then '-1.2338000'
    when lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%cbd%' then '-1.2864000'
    when lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%city centre%' then '-1.2864000'
    when lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%city center%' then '-1.2864000'
    when lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%nairobi%' then '-1.2864000'
    else latitude
  end,
  longitude = case
    when lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%westlands%' then '36.8108000'
    when lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%kilimani%' then '36.7872000'
    when lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%lavington%' then '36.7617000'
    when lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%kileleshwa%' then '36.7831000'
    when lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%parklands%' then '36.8242000'
    when lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%upper hill%' then '36.8154000'
    when lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%ngong road%' then '36.7852000'
    when lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%langata%' then '36.7641000'
    when lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%karen%' then '36.7076000'
    when lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%ruaka%' then '36.7756000'
    when lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%runda%' then '36.8019000'
    when lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%kasarani%' then '36.8981000'
    when lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%embakasi%' then '36.9182000'
    when lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%donholm%' then '36.8886000'
    when lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%south b%' then '36.8422000'
    when lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%southb%' then '36.8422000'
    when lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%south c%' then '36.8209000'
    when lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%southc%' then '36.8209000'
    when lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%thika road%' then '36.8777000'
    when lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%cbd%' then '36.8172000'
    when lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%city centre%' then '36.8172000'
    when lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%city center%' then '36.8172000'
    when lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%nairobi%' then '36.8172000'
    else longitude
  end
where latitude is null
  and longitude is null
  and (
    lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%westlands%'
    or lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%kilimani%'
    or lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%lavington%'
    or lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%kileleshwa%'
    or lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%parklands%'
    or lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%upper hill%'
    or lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%ngong road%'
    or lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%langata%'
    or lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%karen%'
    or lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%ruaka%'
    or lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%runda%'
    or lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%kasarani%'
    or lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%embakasi%'
    or lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%donholm%'
    or lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%south b%'
    or lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%southb%'
    or lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%south c%'
    or lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%southc%'
    or lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%thika road%'
    or lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%cbd%'
    or lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%city centre%'
    or lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%city center%'
    or lower(coalesce(location, '') || ' ' || coalesce(address, '')) like '%nairobi%'
  );
